language: php

dist: trusty

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.3
    - php: nightly
    - php: 7.4snapshot
    - deploy:
        script: composer build
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/lio.phar
        skip_cleanup: true
        on:
          branch: phar_artifact
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit

before_deploy:
  - composer build

#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: build/lio.phar
#  skip_cleanup: true
#  on:
#    branch: phar_artifact
#    php: 7.3