language: php

dist: trusty

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.3
    - php: nightly
    - php: 7.4snapshot
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit

before_deploy:
  - composer build

jobs:
  include:
    - stage: deploy
      php: 7.3
      provider: releases
      file: build/lio.phar
        skip_cleanup: true
        on:
          branch: phar_artifact
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: build/lio.phar
#  skip_cleanup: true
#  on:
#    branch: phar_artifact