language: php
dist: trusty
sudo: false
stages:
  - name: test
  - name: deploy
    if: tag IS present
jobs:
  include:
    - php: 7.2
      before_script: composer install --dev
    - php: 7.3
      before_script: composer install --dev
    - php: 7.4snapshot
      before_script: composer install --dev
    - php: nightly
      before_script: composer install --dev
    - stage: deploy
      script: composer build
      before_script: composer install
      php: 7.3
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/lio.phar
        skip_cleanup: true
        on:
          tags: true
        name: $TRAVIS_TAG
  allow_failures:
    - php: nightly
    - php: 7.4snapshot